### PR TITLE
[Nette] Update MakeGetComponentAssignAnnotatedRectorTest configs

### PR DESCRIPTION
**Pull request by alexndlm**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
I've fixed the PHPStan paths in `main` branch. Please rebase

The ECS will fail, as there is unused import that you have to remove.

**Comment by alexndlm** [comment]
Thanks. Have done.

**Comment by TomasVotruba** [comment]
Thank you :+1:

**Comment by alexndlm** [comment]
Thank you too :)

**Pull request merged**
